engines:
  eslint:
    enabled: true
  csslint:
    enabled: true
  duplication:
  	enabled: true
    config:
    	languages:
      - node
      	#mass_threshold: 30
      - javascript
ratings:
  paths:
  - app/**
  - lib/**
  - "**.js"
  - "**.jsx"
exclude_paths:
- spec/**/*
- "**/vendor/**/*"