engines:
  eslint:
    enabled: true
  csslint:
      enabled: true

ratings:
     paths:
     - "**.js"
     - "**.jsx"
     - "**.pcss"
     - "**.sass"
     - "**.scss"
     - "**.less"

exclude_paths:
  - "spec/**/*"
