language: node_js
sudo: true
node_js:
  - '0.12'
cache:
  directories:
    - node_modules
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
after_success:
  - npm run coveralls &  codeclimate-test-reporter < lcov.info